### PR TITLE
Remove patch size default assignment on load begin

### LINKED ISSUE #1197: OOM with models library models with varying dimensions
Steps to reproduce:

1. Open Kicked Rotator (or any other models library model with a very large patch size, but a small number of patches)
2. Open Fire (or any other model with a large number of patches)

Result: OOM

The OOM occurs here: https://github.com/NetLogo/NetLogo/blob/b6bdee202500e3b1ec70867ee0edcfdd02d28ffc/netlogo-gui/src/main/window/View.java#L171

I think what's happening is that the patch size from the previous model is being used with the dimensions of the new model. Indeed, printlning `getWidth` and `getHeight` there gives:

```
[info] 357
[info] 357
[info] 27108
[info] 27108
# OOM happens
[info] 502
[info] 502
```

Note that this *only* happens with models library models.

### PR DESCRIPTION
**Pull request by qiemem**
Fixes #1197

### CODE REVIEW

**Comment by mrerrormessage** [comment]
I'll want to test this a bit, but I think it sounds good on the basis of what you've posted. Are there ever cases where *this change* would cause NetLogo to allocate a much larger view than needed? What happens if a prior model has a ludicrously large patch size and/or zoom and the new model has a large number of patches?

**Comment by qiemem** [comment]
Ah, it actually still breaks if you're super zoomed in. Man, having zoom be an additive constant on the patch size seems pretty silly to me...

**Comment by mrerrormessage** [comment]
Agreed. I'm not 100% sure about how to make the fix here, but I have a few ideas:

1. It appears that we set the view to be not visible between when the model starts loading and when the model finishes loading. This doesn't (apparently) prevent it from being rendered. Can we find a way to prevent that?
2. We set the renderer on on load begin. Can we set it to some do-nothing renderer for the duration of the loading period, then set it to the "real" renderer when the load finishes?
3. Can / should we disable drawing the whole interface area for the duration of model load?

I don't know whether you've attempted any of these or looked into them, I might have some time to investigate further later today.

**Comment by qiemem** [comment]
These problems all derive from the fact that the magnitude of the effect of zoom depends on the patch size. Thus, patch size changes trigger changes in zoom level (which was the first problem) and patch size changes change how zoom is applied (which is what's happening now). Zoom really should be independent of patch size, instead applied directly as a scalar to the dimensions. That is, the dimensions of the view are currently calculated as:

```
worldWidth * (patchSize + zoom)
worldHeight * (patchSize + zoom)
```

when a more robust approach would be

```
worldWidth * patchSize * zoom
worldHeight * patchSize * zoom
```

This way, patch size and zoom level won't depend on each other at all. I'm honestly surprised this isn't how zoom already works.

**Comment by mrerrormessage** [comment]
This looks good to me. 

While testing this, I uncovered a corner case in which the zoom and model size are such that they cause the graphics system to error due to arithmetic wraparound (width*height = area: `105969 * 105969 = -1655472927`). This PR doesn't cause this bug, but we should probably cap the zoom level at some point to prevent problems like that (or throw our own error to indicate that the view is too large).

**Pull request merged**
