### PR TITLE
Update to Scala 2.12.18

### PR DESCRIPTION
**Pull request by EwoutH**
Update from Scala 2.12.17 to [2.12.18](https://github.com/scala/scala/releases/tag/v2.12.18). This includes a update from ASM 9.3 to 9.5, which improved JDK 20 and 21 support.

### CODE REVIEW

**Comment by EwoutH** [comment]
CI [got stuck](https://github.com/NetLogo/NetLogo/actions/runs/5259690266/jobs/9505593685?pr=2119#step:6:212) on this new linting feature https://github.com/scala/scala/pull/10313, what's the proper way to handle these cases of integral divisions?

**Comment by LaCuneta** [comment]
Whoops, I forgot to advise you about the test compilation, too.  Sorry about that!  It'd be `netlogo / Test / compile` and `headless / Test / compile`.

**Review by LaCuneta — APPROVED** [review]
Thanks for your persistence in all the linting changes!

**Comment by EwoutH** [comment]
You're welcome! Thanks for the swift feedback and merging!

**Pull request merged**
