### PR TITLE
Add CITATION.cff

### LINKED ISSUE #1944: add CITATION file to repo?
seems like something Uri would want y'all to add, now that GitHub offers the feature: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files

(thought prompted by seeing https://github.com/lampepfl/dotty/pull/13357)

### PR DESCRIPTION
**Pull request by bevsxyz**
Fixes  #1944

### CODE REVIEW

**Review by LaCuneta — CHANGES_REQUESTED** [review]
Thank you for your contribution!  I appreciate it.  I do not know much about the `CITATION.cff` format, so I did some reading.  My apologies in advance if I get something wrong here.

Small thing:  The release date of NetLogo 6.2 was December 26th, 2020.  Where did you get that January date?

When I view the changes [on your fork of the repo on GitHub](https://github.com/bevsxyz/NetLogo) I don't see any information in the "Cite this repository" area, just a link to this file (image below).  Is this due to the content of the file being different than GitHub expects, or because your repo is a fork, perhaps?  In any case, I know that what we would want is for users to see the citation on the GitHub page exactly as it appears [in our documentation](http://ccl.northwestern.edu/netlogo/docs/faq.html#how-do-i-cite-netlogo-or-hubnet-in-a-publication).  If all it does is link to this file, I don't think that will be helpful for us as people would then have to interpret the file to create the citation; we'd really prefer people cite exactly as outlined in the docs.

Citation

Maybe related to the above, I see your file used the `preferred-citation` section.  I read that that section is used to link to something like a journal paper instead of the software itself, but here it links to our CCL website.  What was the reason for using this section instead of just having the "main" software information generate the citation?  I don't need this to change, I'm just trying to understand the usage.

I don't look forward to having one more place to manually update the version and release date, but automating that would likely be beyond the scope of the original issue.  We could update our releasing wiki docs with the extra step for now.

If we can get this updated so that it does display the exact citation we want on the main GitHub repo page, I think we can get it merged.

**Comment by SethTisue** [comment]
I'm at least mildly curious whether anyone is interested in pursuing this further.

(Historically, Uri was always highly concerned with encouraging users to cite NetLogo and cite it correctly.)

**Comment by bevsxyz** [comment]
@LaCuneta I got the date at the time of Github releases. I have fixed it now by referring to the NetLogo release page for the current latest version. I think at the time I made the initial commit `preferred-citation` was required for non-GitHub links. Apparently, the citation already works on my fork now so perhaps I don't have to do that. Will confirm and let you know. 

Automating is something I haven't come across yet but I would love to see it. But then the release date will have the GitHub releases dates, for which I can see one from two days ago.

**Comment by bevsxyz** [comment]
@SethTisue @LaCuneta Sorry for the delayed response. I was held up with things

**Comment by bevsxyz** [comment]
I remember why I went with `preferred-citation`, because without it the release date would be present in the citation and not the original year. I just created a temporary fork just to check it. https://github.com/Bevanstanely/NetLogows/tree/hexy

**Comment by bevsxyz** [comment]
> Thank you for your contribution! I appreciate it. I do not know much about the `CITATION.cff` format, so I did some reading. My apologies in advance if I get something wrong here.
> 
> Small thing: The release date of NetLogo 6.2 was December 26th, 2020. Where did you get that January date?
> 
> When I view the changes [on your fork of the repo on GitHub](https://github.com/bevsxyz/NetLogo) I don't see any information in the "Cite this repository" area, just a link to this file (image below). Is this due to the content of the file being different than GitHub expects, or because your repo is a fork, perhaps? In any case, I know that what we would want is for users to see the citation on the GitHub page exactly as it appears [in our documentation](http://ccl.northwestern.edu/netlogo/docs/faq.html#how-do-i-cite-netlogo-or-hubnet-in-a-publication). If all it does is link to this file, I don't think that will be helpful for us as people would then have to interpret the file to create the citation; we'd really prefer people cite exactly as outlined in the docs.
> 
> Citation
> 
> Maybe related to the above, I see your file used the `preferred-citation` section. I read that that section is used to link to something like a journal paper instead of the software itself, but here it links to our CCL website. What was the reason for using this section instead of just having the "main" software information generate the citation? I don't need this to change, I'm just trying to understand the usage.
> 
> I don't look forward to having one more place to manually update the version and release date, but automating that would likely be beyond the scope of the original issue. We could update our releasing wiki docs with the extra step for now.
> 
> If we can get this updated so that it does display the exact citation we want on the main GitHub repo page, I think we can get it merged.

It will show APA and BibTeX formats for copying.

**Review by LaCuneta — CHANGES_REQUESTED** [review]
@bevsxyz No worries on the delay.  Thanks for working on this again.  Now when I go to your fork's GitHub page, I see the **Cite this repository** button, and clicking it does give me the option to quickly copy the APA version.  So that's progress.

Here is what it copies:

> Wilensky, U. (1999). NetLogo [Computer software]. https://ccl.northwestern.edu/netlogo/

And here is our preferred citation from the docs:

> Wilensky, U. (1999). NetLogo. http://ccl.northwestern.edu/netlogo/. Center for Connected Learning and Computer-Based Modeling, Northwestern University, Evanston, IL

I think we'd be okay having the **[Computer software]** note in there, but to accept this PR I know we'll need our organization information added so what you see on GitHub matches our preferred citation as closely as possible.

**Comment by bevsxyz** [comment]
This is the current version. I don't think the Github APA formatting would allow the link to come in the middle. Will that be alright? Btw I am defining the citation type as an article. Another option is manual. Everything else messes up further.

> Wilensky, U. (1999). NetLogo. Center for Connected Learning and Computer-Based Modeling, Northwestern University, Evanston, IL. https://ccl.northwestern.edu/netlogo/

**Comment by LaCuneta** [comment]
@bevsxyz Thanks for trying to get it to match!  I'll check with the powers that be and see if it's close enough to merge, hopefully I'll be able to get back to you early next week.

**Review by LaCuneta — APPROVED** [review]
We got approval, thanks again for your work on this!

**Comment by bevsxyz** [comment]
Thanks for accepting the PR. ❤️

**Pull request merged**
