### PR TITLE
Use markdown for documentation. Closes #616

### LINKED ISSUE #616: User Manual should be in Markdown, not HTML
the HTML is hard to hand-maintain

one section of the User Manual is already in Markdown, and the build has support for doing the HTML conversion, so it would just need to be extended to other sections. it could happen a section at a time if redoing the whole manual at once is too daunting

`pandoc` is pretty good at converting markup formats. with a little luck, the results would only need minor manual cleanup

### PR DESCRIPTION
**Pull request by Idloj**
@mrerrormessage, I have also made changes in submodules (mainly change links to match new anchor names). Can you create a branch on the following submodules, please? gis, matrix, nw, r, rnd, sound, models. (Is it possible to grant push access to me on a specific branch?)

### CODE REVIEW

**Comment by mrerrormessage** [comment]
Thanks for the PR! We're preparing for the next release over the next week, then I'll be on vacation, so I don't think I'll be reviewing this until around August 1.

**Comment by Idloj** [comment]
@mrerrormessage Anything I still need to do to get it merged?

**Comment by Idloj** [comment]
Saw your comment on gitter only now

**Comment by mrerrormessage** [comment]
OK, I've reviewed the actual pages of the manual (but not the code that powers them yet, since that may have some changes based on this feedback).

This looks awesome! I was impressed at how closely this matched the html user manual.

There are a few minor issues I would like sorted out before merging:

* One of the tables in hubnet-authoring.html shows backquotes within a table element
* interface.html table has an invalid HTML section in it's big table
* `[[ show ]]` appears on interfacetab.html.
* programming .html has "if your anonymous procedure if your anonymous procedure"

When generating the manual PDF, there are now three broken image links (referenced by the GIS extension README) which worked before. Do you know why these might have broken?

Finally (and this may have been configured prior to this pull request) each page now has a table-of-contents at the top. I don't know that this is desirable for every page. Further, these tables of contents index each element, which means that some of our longer pages (like the programming guide) end up opening to just the table of contents. Additionally, we want to be able to disable table-of-contents when we're building the PDF version of the manual. The PDF manual has one big table-of-contents, so we don't need smaller sectional tables.

If you aren't sure about the PDF image links and table-of-contents stuff. I would be willing to merge this and fix these problems after the minor formatting issues are addressed. The manual PDF is difficult to work with and the link stuff is a bit complex. 

Thanks again for doing this. I anticipate it will make NetLogo manual changes much smoother in the future.

**Comment by Idloj** [comment]
The minor issues are dealt with. The gis submoudle will need to get updated, though. I have the changes locally and it works, I just need a way to merge it in, probably like we've done it earlier (PRs to a temporary branch). This will also allow the images to appear on Github README.

As for the TOCs, they appear in the PDF in hexy too, but I'll take care of eliminating them from the PDF (just wanted to prove myslf innocent :man_shrugging:).

I've put TOCs in almost all pages (those that weren't very short). Removing them is as simple as deleting the `[TOC]`, or you may want to consider lowering the level for some of them (This can be done by writing something like `[TOC levels=2]`, which will put only `h2`s in the TOC). I can do it myself if you let me know what pages do you want without TOC or with a more shallow one, or you can merge it as its. I don't mind.

**Comment by mrerrormessage** [comment]
I just created a documentation-updates branch on the GIS extension. Please open a PR there and I'll review/merge.

> As for the TOCs, they appear in the PDF in hexy too, but I'll take care of eliminating them from the PDF (just wanted to prove myslf innocent 🤷‍♂️).

That's true. This PR just caused me notice them, since many pages had a 1-5-line table of contents and this PR turned those into a 5-10+-line table of contents.

I would like to see something like `[TOC levels=2]` and I would appreciate it if you could take care of that (if you'd rather not, let me know and I can merge this in and do it). The rule of thumb I would use is that tables of contents shouldn't have nesting - so the items should reflect major headings. I would assume that is `[TOC levels=2]`, but it might vary depending on the page (some pages might have their headings at level 3 instead).

One more thing that I noticed is that the left sidebar formatting is strange.

screen shot 2017-08-23 at 10 01 40 am
screen shot 2017-08-23 at 10 01 44 am

Fixing this is just a matter of putting "NetLogo" and "User Manual" in separate `<span>` elements.

Thanks again for the hard work on this!

**Comment by mrerrormessage** [comment]
@Idloj , sorry I missed all those submodules. Branches have been created on all of them.

**Comment by Idloj** [comment]
Thanks, I'll open PRs today

**Comment by mrerrormessage** [comment]
@Idloj , I believe I've merged all the pull requests for this. Is it ready for re-review? If so I can look at it tomorrow.

**Comment by Idloj** [comment]
The `models` PR is still open, after it's merged I'll update the PR to use the correct submodule commits.

Note: I still hadn't had the chance to look into the `[[show]]` problem in `interfacetab.html`

**Comment by mrerrormessage** [comment]
OK, models PR has been merged in. Let me know when the `[[show]]` problem has been looked at and I'll re-review.

**Comment by Idloj** [comment]
Just fixed

**Comment by mrerrormessage** [comment]
Upon re-review, things look generally good, but there are still a few small issues:

* There are still backquotes in the table on hubnet-authoring. The code contained in these backquotes doesn't (necessarily) need to be displayed in monospace, but the backquotes should not appear.
* The "Tabs" section of the table in interface.html still doesn't show up correctly (it shows up as html for a table instead of a table) itself.
* To everyone's great frustration (I'm sure) the links in the matrix extension page now render incorrectly. For instance [this link](https://github.com/NetLogo/Matrix-Extension/pull/13/files#diff-04c6e90faac2675aa89e2176d2eec7d8R546) now renders as `#matrix::forecast-linear-growth`. Before your updates, this link rendered correctly. I couldn't figure out exactly why this was happening 🤷‍♂️. I did notice that you changed how github-style markdown links were being processed in flexmark. Do you have any ideas why these changes might have happened? It should be noted that other extensions have links that work fine (for instance the link to r:clear in [this section of the r extension README](https://github.com/NetLogo/R-Extension/blob/hexy/README.md#rclearlocal)).

As always, I'm happy to help in any way I can. Thanks for continuing to work on this!

**Comment by Idloj** [comment]
I'm sorry but I can't see any of these issues. I even deleted `netlogo-gui/docs` and generated them again just to make sure, but I can't see any of these.

**Comment by mrerrormessage** [comment]
Hmm....I deleted netlogo-gui/docs, regenerated and these issues went away too. So this looks good and I'm merging it. Thanks again for all the hard work on this! Sorry for the delays in getting this merged, it looks awesome and is a big step forward.

**Comment by SethTisue** [comment]
@Idloj this is awesome

**Pull request merged**
