### PR TITLE
No Exception while right clicking and dragging a widget

### PR DESCRIPTION
**Pull request by Akarshit**
Fix for #436 
Implemeted what was said [here](https://github.com/NetLogo/NetLogo/issues/436#issuecomment-170176997).

### CODE REVIEW

**Comment by mrerrormessage** [comment]
This works great on Linux, but still shows errors on Mac and Windows.

I was able to get it working on all three with the following code:
```diff
diff --git a/src/main/org/nlogo/app/WidgetWrapper.java b/src/main/org/nlogo/app/WidgetWrapper.java
index 68b978b..600dfb0 100644
--- a/src/main/org/nlogo/app/WidgetWrapper.java
+++ b/src/main/org/nlogo/app/WidgetWrapper.java
@@ -474,7 +474,7 @@ public strictfp class WidgetWrapper
   public int startPressY;

   public void mousePressed(java.awt.event.MouseEvent e) {
-    if (e.isPopupTrigger() && selected() && !org.nlogo.awt.Mouse.hasButton1(e)) {
+    if (e.isPopupTrigger() && mouseMode() != MouseMode.DRAG) {
       doPopup(e);
       return;
     }
@@ -577,7 +577,7 @@ public strictfp class WidgetWrapper
   }

   public void mouseReleased(java.awt.event.MouseEvent e) {
-    if (e.isPopupTrigger()) {
+    if (e.isPopupTrigger() && mouseMode() != MouseMode.DRAG) {
       doPopup(e);
       return;
     } else if (org.nlogo.awt.Mouse.hasButton1(e)) {
```

If you want to apply these changes to your branch, I'll go ahead and merge it in and save opening up a new PR.

**Comment by Akarshit** [comment]
@mrerrormessage OK i will make the required changes in this PR only.

**Comment by Akarshit** [comment]
Done.

**Comment by mrerrormessage** [comment]
Terrific, thanks so much!

**Pull request merged**
