### PR TITLE
Improve singular breed lookup performance

### LINKED ISSUE #1856: Non-constant time to look up agent by id when using breed keyword
I ran into a unexpected performance issue in NetLogo 6.1.1 when attempting to get a variable value from a turtle by its "who" index, and found that there may be an issue related to breeds. 

When looking up an agent with `turtle i`, lookup time is constant as expected. However, if referencing by breed name, e.g. `tuna i` then lookup time increases roughly linearly with `i`. That is, the lookup time for `[variable] of tuna 0` is similar to `[variable] of turtle 0` but `[variable] of tuna 10000` is very slow. 

Below is a simple test model that demonstrates the issue along with screenshots of output. The code assumes UI inputs for "N," "turtleToQuery," and "breed?". I am curious if this can be reproduced. 

```
breed [tunas tuna]
turtles-own [someVariable]
globals [maxWho]

to spawn-turtles
  create-tunas N [
    setxy random-xcor random-ycor
    set someVariable 1
  ]
end

to setup
  clear-all
  spawn-turtles
  set turtleToQuery 0
  set maxWho max [who] of turtles
  reset-ticks
end

to go
  reset-timer
  ask turtles [
    ifelse (breed?) [
      let j [someVariable] of tuna turtleToQuery
    ]
    [
      let j [someVariable] of turtle turtleToQuery
    ]
  ]
  set turtleToQuery turtleToQuery + 1
  if (turtleToQuery > maxWho) [set turtleToQuery maxWho]
  show timer
  tick
end
```
BreedBug1
BreedBug2

### PR DESCRIPTION
**Pull request by qiemem**
Fixes #1856
Makes singular breed lookup constant time (from linear)
Makes breed containment check log time (from linear)

### CODE REVIEW

**Comment by brandesNW** [comment]
The following files need to be updated to be consistent with the new code:
./test/benchdumps/GasLabNew.txt
./netlogo-headless/test/benchdumps/GasLabNew.txt

**Comment by qiemem** [comment]
Ah woops. Sorry about that. You okay if I force push on this branch?

**Comment by qiemem** [comment]
Oh, sorry, could you remind me how to regenerate the dump files?

**Comment by LaCuneta** [comment]
I think [these directions](https://github.com/NetLogo/NetLogo/wiki/Building#which-tests-do-i-run) are still correct: `netlogo/dump bench` and `headless/dump bench`

**Comment by qiemem** [comment]
Ah! Missing the `bench`. Thanks! Force pushed an amended commit.

**Comment by qiemem** [comment]
Looks like `InSanityRadius::InSanityRadius_Turtles_3D` failed in Jenkins. It passes locally for me and I don't see any relevant primitives used in that test, so not sure what's going on here.

**Comment by LaCuneta** [comment]
Yeah, I'll make a note to look into that, I don't think it's related to this PR.  The tests passed when re-run a second time.

**Pull request merged**
