### PR TITLE
Port headless compiler

### PR DESCRIPTION
**Pull request by mrerrormessage**
Merges NetLogo and NetLogo-Headless back into one happy project.

This is not *quite* ready for merge, but I'm posting for review, as the changes are substantial.

### CODE REVIEW

**Comment by SethTisue** [comment]
wow, very cool.

there's no way I can do a full review on this, but is there anything in particular you'd like me to look at it?

**Comment by mrerrormessage** [comment]
The changes in `Observer` and `World` (both in netlogo-gui/src/main/agent) are the most substantial, in my opinion. Many files changed only a little, but those two changed substantially. All tests pass for netlogo, but review would still be appreciated.

**Comment by SethTisue** [comment]
ok, I can't this week, but I should be able to next week.

**Comment by mrerrormessage** [comment]
Sounds great! I may go ahead and merge it, but changes could still be made.
Thanks!

Robert

**Comment by SethTisue** [comment]
well, this got lost in my life upheaval this year. but the test coverage for Observer and World is very solid, and as for the GUI aspects, that's what betas are for ;-)

**Pull request merged**
