### PR TITLE
Changed the layout to grouplayout and formatted a little bit

### PR DESCRIPTION
**Pull request by Akarshit**
The find replace window looked like this before:
screenshot from 2016-04-15 14 04 28
Now the window looks like this:
screenshot from 2016-04-15 13 50 25

### CODE REVIEW

**Comment by Idloj** [comment]
Maybe "phrase not found" should start with a capital p?

**Comment by mrerrormessage** [comment]
Thanks for the PR! I'm planning to review this on Monday.

**Comment by Akarshit** [comment]
@Idloj waiting for the review from @mrerrormessage so that I can implement all the changes together.

**Comment by mrerrormessage** [comment]
This looks good in general, but it doesn't look right on Mac OS X:
screen shot 2016-04-18 at 9 57 22 am
Do you know how this could be adjusted to look right? I tried a few simple things but wasn't able to get them working. I don't have time this morning to troubleshoot this in more depth, but if you have some ideas I'd be happy to try them out and let you know whether any of them work.

**Comment by mrerrormessage** [comment]
OK, I'm closing out all PRs on the 5.x branch. Are you interested in continuing to work on this PR on hexy?

**Comment by mrerrormessage** [comment]
Closing this as it's a 5.x PR. Would accept if it was ported to hexy.

**Pull request closed without merging**
