### PR TITLE
JFlex 1.5.1 (was 1.4.3)

### LINKED ISSUE #1984: Compilation error in JFlexRunner.scala when building with JFlex 1.5+
When building with JFlex 1.5 or newer, it suddenly can't seem to find JFlex anymore, and the [following error](https://github.com/EwoutH/NetLogo/runs/4164358300?check_suite_focus=true#step:6:197) presents itself on compilation. The error is identical for JFlex 1.5.1, 1.6.1 and 1.8.2.
```
Error:  /home/runner/work/NetLogo/NetLogo/project/JFlexRunner.scala:30:5: not found: value JFlex
Error:      JFlex.Main.main(Array("--quiet", "-d", cacheDirectory.getPath, (autogenFolder / "flex" / (kind + ".flex")).asFile.getAbsolutePath.toString))
Error:      ^
Error:  one error found
Error:  (Compile / compileIncremental) Compilation failed
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
Error: Process completed with exit code 1.
```
The error is located in [project/JFlexRunner.scala](https://github.com/NetLogo/NetLogo/blob/6.2.1/project/JFlexRunner.scala#L30). JFlex can be updated in [project/plugins.sbt](https://github.com/NetLogo/NetLogo/blob/6.2.1/project/plugins.sbt#L28).

Part of #1968.

### PR DESCRIPTION
**Pull request by SethTisue**
fixes #1984

note that I didn't try to go to latest JFlex, which is 1.8.2, according to https://www.jflex.de/changelog.html

I figured we should take this a step at a time.

### CODE REVIEW

**Comment by SethTisue** [comment]
draft for now because I should try and resolve this:

```
sbt:root> headless/Test/compile

Warning in line 12: The 'switch' code generation method is deprecated and will be removed in JFlex 1.6.

Warning: Emitting deprecated InputStream constructor. In JFlex 1.6, the default will be to NOT emit this constructor. The inputstreamctor option will cause this constructor to be emitted in JFlex 1.5 and 1.6; the version after 1.6 will never emit this constructor.
```

**Comment by SethTisue** [comment]
> The 'switch' code generation method is deprecated and will be removed

our `ImportLexer.flex` said "this option decreases code size; see JFlex documentation" but the difference in code size in our case is less than 2% (17279 bytes vs 17612 bytes)

**Comment by SethTisue** [comment]
the "deprecated InputStream constructor" thing was easy to handle by passing `--noinputstreamctor`

**Comment by SethTisue** [comment]
ping :-)

**Review by LaCuneta — APPROVED** [review]
Ran the code gen locally and everything looks good to me.  Thank you for this!

**Pull request merged**
