### PR TITLE
Jump to definition

### LINKED ISSUE #544: feature: "Jump to Definition" in Code tab
we're tantalizing close to already having this in that we already have code for:
- the Procedures menu, which lets you jump to any procedure definition that you choose by name
- the F1 key, which finds the token next to the cursor and takes an action depending on what it is

so this would be an easy starter project for someone (inside or outside the CCL) looking to improve the NetLogo editor/IDE

probably the F1 key ought to be reused for "Jump to definition"? if you F1 a primitive you get the User Manual, if you F1 your own procedure, it jumps to the definition.

### PR DESCRIPTION
**Pull request by Idloj**
Close #544
Previously #635(see previous discussions), now on a separate feature branch.

[Review on Reviewable](https://reviewable.io/reviews/netlogo/netlogo/653)

### CODE REVIEW

**Comment by SethTisue** [comment]
any news on this?

**Comment by Idloj** [comment]
What do you mean?

**Comment by SethTisue** [comment]
I'm asking @frankduncan if this is going to be merged.

**Comment by frankduncan** [comment]
Yep.  Just now catching up with stuff

**Comment by frankduncan** [comment]
This is super neat, btw.  Thanks a ton!

**Pull request merged**
