### PR TITLE
JFlex 1.8 (was 1.5)

### PR DESCRIPTION
**Pull request by SethTisue**
sequel to #2004 

reference: https://www.jflex.de/changelog.html

### CODE REVIEW

**Comment by SethTisue** [comment]
CI liked 1.6. let's try 1.7

**Comment by SethTisue** [comment]
CI liked 1.7. trying 1.8...

**Comment by SethTisue** [comment]
I should check and see if this helps with #1533

**Comment by SethTisue** [comment]
hmm

```
Error:  /home/runner/work/NetLogo/NetLogo/netlogo-gui/target/src_managed/main/org/nlogo/agent/ImportLexer.java:16:1: java.lang.SuppressWarnings is not a repeatable annotation type
Error:  @SuppressWarnings("FallThrough")
```

**Comment by SethTisue** [comment]
`LoggerTests` failed, but that doesn't seem plausibly related. re-running.

**Comment by SethTisue** [comment]
by the way, I hadn't realized until just now that JFlex was no longer used for lexing NetLogo itself. only `ImportLexer` uses it. so I see this is a lower-stakes change than I'd realized. well, all the more reason to get on the latest version

**Comment by SethTisue** [comment]
CI likes it, and 1.82 is the latest version

**Review by LaCuneta — APPROVED** [review]
Looks good to me.  Funny that they wound up including the same fallthrough suppression we did.

**Pull request merged**
