### PR TITLE
WIP: CI: Add AppVeyor configuration

### PR DESCRIPTION
**Pull request by EwoutH**
I'm working on an AppVeyor configuration for automatic Windows builds, but right now [my builds](https://ci.appveyor.com/project/EwoutH/netlogo) fail at the following part when compiling with `sbt all`:
```
[error] java.io.FileNotFoundException: C:\projects\netlogo\models\Code Examples\Info Tab Example.nlogo (The system cannot find the file specified)
[error] 	at java.io.FileInputStream.open0(Native Method)
[error] 	at java.io.FileInputStream.open(FileInputStream.java:195)
...
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (netlogo / htmlDocs) java.io.FileNotFoundException: C:\projects\netlogo\models\Code Examples\Info Tab Example.nlogo (The system cannot find the file specified)
```
Does anyone have any idea what the problem is here?

### CODE REVIEW

**Comment by EwoutH** [comment]
@LaCuneta Do you know how this error is caused? Or what I should change to successfully build on Windows?

**Comment by SethTisue** [comment]
`git submodule update` should be `git submodule update --init`, I think

**Comment by EwoutH** [comment]
Thanks @SethTisue, I should have seen that. It fixed the `sbt all` error. The [guide on the Wiki](https://github.com/NetLogo/NetLogo/wiki/Windows-Setup) states that the following step is running `sbt netlogo/run` to compile and run the NetLogo GUI. The problem with that in a CI environment is that it [keeps running](https://ci.appveyor.com/project/EwoutH/netlogo/builds/31777548) indefinitely. Is there a way to only compile the GUI without running it?

**Comment by Idloj** [comment]
`netlogo/compile` should do it

**Comment by EwoutH** [comment]
Thanks, looks like that works. It now produces a Java executable `netlogo-6.1.1.jar`. Unfortunately I get an error running it:

- `Error: A JNI error has occurred, please check your installation and try again`, followed by `A Java Exception has occurred`.

This with Java 8 Update 241 on Windows 10 (1909) 64-bit. Same issue on a different but comparable system.

Is this a known error? If so, how can I fix it? Also, is there a way to generate an installer or just a regular executable? Like when you download Netlogo from http://ccl.northwestern.edu/netlogo (there must be a release/deploy script or something).

**Comment by EwoutH** [comment]
If anyone could test the `netlogo-6.1.1.jar` that [AppVeyor](https://ci.appveyor.com/project/EwoutH/netlogo/build/artifacts) produces that would be great!

**Comment by SethTisue** [comment]
> If anyone could test the netlogo-6.1.1.jar that AppVeyor produces that would be great

you could [jardiff](https://github.com/scala/jardiff) it with a JAR produced by other means

**Comment by SethTisue** [comment]
> Also, is there a way to generate an installer or just a regular executable? 

this appears to be documented in `dist/BUILDING.md` (though whether the info is up-to-date, idk)

**Comment by EwoutH** [comment]
Thanks for the quick reply!

> you could jardiff it with a JAR produced by other means

Will give it a try. Does NetLogo publish nightlies by any chance? Or Jenkins artifacts?

> this appears to be documented in dist/BUILDING.md (though whether the info is up-to-date, idk)

Thanks, I will review the AppVeyor build script against it.

Currently I got the following error btw:
```
java -jar "C:\Users\Ewout\Downloads\netlogo-6.1.1.jar"
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Function1
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: scala.Function1
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more
```
Java version for reference:
```
java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) Client VM (build 25.241-b07, mixed mode, sharing)
```

**Comment by SethTisue** [comment]
re `java.lang.NoClassDefFoundError: scala/Function1`, that's because the NetLogo JAR isn't self-contained; the NetLogo GUI expects the current working directory to be a full NetLogo installation. (this particular error is because as part of that, it expects a lot of other JARs to be present in the same directory as the NetLogo JAR, including `scala-library-2.12.8.jar`)

(I am leaving some of your questions unanswered because I haven't actually worked on NetLogo in years so there are many questions I no longer know the answers to)

**Comment by EwoutH** [comment]
@brandesNW Hi, thanks for the reply!

The end goal is to create an AppVeyor configuration that produces complete (static) NetLogo builds for at least the Windows x64 plaform to be able to quickly test changes and new features. This is a work in progress since I'm still figuring out the build/compile process, including dependencies.

`JAVA_HOME` is always defined since Java is [included](https://www.appveyor.com/docs/windows-images-software/#java) in the Visual Studio 2019 image by default.

I'm currently still stuck on the error above (`Exception in thread "main" java.lang.NoClassDefFoundError: scala/Function1`), something is missing from the build (or packaging) script.

**Comment by brandesNW** [comment]
Hi Ewout,
We have successfully integrated your other pull request 1824, updating sbt and scala. Thanks again. 
As I  understand it, the AppVeyor configuration file is currently a work in progress that is targetted to Windows x64. If that is the case it seems more appropriate for you to keep it in your own repo, than for us to add it to the NetLogo repository.
On the other hand, we are always looking for ways to automatize and improve our build process. We need to develop and distribute code for  Windows x32, Windows x64, Linux and MacOS X. If we were able to use AppVeyor (for no charge as an open software product) we would be interested in incorporating the configuration file.
We hope you keep working with NetLogo, and hope you get the config file working for Windows x64,  However I will close this pull request, unless you can explain  the value of doing so at this point in its development.
Thanks,
Aaron

**Comment by EwoutH** [comment]
@brandesNW Yes lets close this. I'm currently working on another branch on the build and CI systems.

More documentation and scripts about building executable/installable Netlogo binaries will be much appreciated though! The [Wiki](https://github.com/NetLogo/NetLogo/wiki) is quite out of date (and maybe not the best way to keep documentation up to date). Dockerfiles can also be considered for building/automation.

**Pull request closed without merging**
