### PR TITLE
Included file content loses synch with compiled state

### PR DESCRIPTION
**Pull request by brandesNW**
Fixes: #[2021](https://github.com/NetLogo/NetLogo/issues/2021)
Addresses: #[1617](https://github.com/NetLogo/NetLogo/issues/1617)
Addresses: #[1832]
(https://github.com/NetLogo/NetLogo/issues/1832)
The model in the zip file can be used for testing.
The tests on the left note work properly. 
There is still a problem with the tests in the right note. 

[save-nls-test.zip](https://github.com/NetLogo/NetLogo/files/8383530/save-nls-test.zip)

### CODE REVIEW

**Review by LaCuneta — CHANGES_REQUESTED** [review]
I left a few comments about minor issues in the code.  

I tested using your sample model as well as re-testing the scenarios outlined in the linked issues.

As you pointed out, if an nls code tab is closed and dirty, the code needs to be reloaded from the file on disk and a compile run again.  I would trace the code that runs when the model loads and see about getting that properly re-run for the closed and dirty file only.

In the notes it says this address issue 1832 (save prompt on input widget change), but I see the same behavior as before and that behavior doesn't really seem related to nls files.  I get the same behavior as described in 1832 without using nls files at all.  How does this address 1832?

This work does seem to mildly improve the situation for issue 1617 (`__reload` with nls files), but not completely.  Here is a scenario (behavior seemed the same with code tab docked or not):

- Open your sample model, run Test, see the expected output.
- Edit the nls file in an external editor.
- Run `__reload` in the Command Center.
- Run Test, see the output is still from the prior code.
- Run `__reload` again in the Command Center.
- Run Test, see the output is still from the prior code.
- Open the nls file in the NetLogo code tab, see the file contents are the updated ones from the external editor.
- Run Test, see the output is even still from the prior code.
- Run `__reload` again in the Command Center.  Note the nls code window closes.
- Run Test, see the output has finally updated the match the current nls file contents.

If you do the same test but with the nls code tab already open before the external edit, the first `__reload` will close the nls code tab, and you have to re-open in again and run `__reload` again before the external edits will "take".

I would expect 1) running `__reload` should leave the nls file editors in place if they are open, with their code updated to whatever is on disk (maybe with a save prompt or error if they are dirty?), and 2) that running `__reload` will get the model running off the code as it is on disk (barring errors, of course).  I checked and item 1 was already an issue in NetLogo 6.0.4, so if that should be worked separately I understand.  But item 2 seems to be the same core problem issue 1617 was described.

Let me know if you have questions on anything.  And thanks.

**Comment by LaCuneta** [comment]
I had one other question tangentially related to these changes - do you know the reason for a separate `saveNeeded` flag in the `TemporaryCodeTab` from the `dirty` flag kept in the parent `CodeTab` class?

**Comment by brandesNW** [comment]
Hi Jeremy,
The brief answer is that the analogous bookkeeping for the main CodeTab is handled by the class DirtyMonitor using the variable _modelDirty.


The dirty flag indicates that a buffer needs to be compiled.
If you switch from  a TemporaryCodeTab to the InterfaceTab, the code will be compiled and the dirty flag will become false. However the buffer has not be saved, so the saveNeeded flag remains true.

For a the main CodeTab, saving is needed when the model is closed or saved.
There is some extra bookkeeping in class DirtyMonitor which has a private var _modelDirty which is used to handle the question of whether a save is needed.


  *   Aaron
  *
--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Jeremy B ***@***.***>
Reply-To: NetLogo/NetLogo ***@***.***>
Date: Wednesday, April 6, 2022 at 3:04 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Aaron Andre Brandes ***@***.***>, Author ***@***.***>
Subject: Re: [NetLogo/NetLogo] Included file content loses synch with compiled state (PR #2023)


I had one other question tangentially related to these changes - do you know the reason for a separate saveNeeded flag in the TemporaryCodeTab from the dirty flag kept in the parent CodeTab class?

**Comment by brandesNW** [comment]
Hi Jeremy,
Thanks for the comments.

I will check out the suggestion

As you pointed out, if an nls code tab is closed and dirty, the code needs to be reloaded from the file on disk and a compile run again. I would trace the code that runs when the model loads and see about getting that properly re-run for the closed and dirty file only.
I had thought that the sequence

      tabs.closeExternalFile(filename)
      if (compileNeeded) {
        new WindowEvents.CompileAllEvent().raiseLater(this)
      }

would handle the issue because the external file was closed, and the method compileAll in the CompilerManager calls compileProcedures (in the non-loading case) which creates a new ExternalFileInterface(fileName)

As you suggest, the file probably needs to be explicitly loaded before the compile, and then closed again.


R.e. Issue 1832 there must be some confusion (perhaps I put in the wrong link). Please look at
Bug on closing NetLogo Window? #1832<https://github.com/NetLogo/NetLogo/issues/1832>
I don’t see anything about widgets

Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Jeremy B ***@***.***>
Reply-To: NetLogo/NetLogo ***@***.***>
Date: Wednesday, April 6, 2022 at 2:52 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Aaron Andre Brandes ***@***.***>, Author ***@***.***>
Subject: Re: [NetLogo/NetLogo] Included file content loses synch with compiled state (PR #2023)


@LaCuneta requested changes on this pull request.

I left a few comments about minor issues in the code.

I tested using your sample model as well as re-testing the scenarios outlined in the linked issues.

As you pointed out, if an nls code tab is closed and dirty, the code needs to be reloaded from the file on disk and a compile run again. I would trace the code that runs when the model loads and see about getting that properly re-run for the closed and dirty file only.

In the notes it says this address issue 1832 (save prompt on input widget change), but I see the same behavior as before and that behavior doesn't really seem related to nls files. I get the same behavior as described in 1832 without using nls files at all. How does this address 1832?

This work does seem to mildly improve the situation for issue 1617 (__reload with nls files), but not completely. Here is a scenario (behavior seemed the same with code tab docked or not):

  *   Open your sample model, run Test, see the expected output.
  *   Edit the nls file in an external editor.
  *   Run __reload in the Command Center.
  *   Run Test, see the output is still from the prior code.
  *   Run __reload again in the Command Center.
  *   Run Test, see the output is still from the prior code.
  *   Open the nls file in the NetLogo code tab, see the file contents are the updated ones from the external editor.
  *   Run Test, see the output is even still from the prior code.
  *   Run __reload again in the Command Center. Note the nls code window closes.
  *   Run Test, see the output has finally updated the match the current nls file contents.

If you do the same test but with the nls code tab already open before the external edit, the first __reload will close the nls code tab, and you have to re-open in again and run __reload again before the external edits will "take".

I would expect 1) running __reload should leave the nls file editors in place if they are open, with their code updated to whatever is on disk (maybe with a save prompt or error if they are dirty?), and 2) that running __reload will get the model running off the code as it is on disk (barring errors, of course). I checked and item 1 was already an issue in NetLogo 6.0.4, so if that should be worked separately I understand. But item 2 seems to be the same core problem issue 1617 was described.

Let me know if you have questions on anything. And thanks.

________________________________

In netlogo-gui/src/main/app/Tabs.scala<https://urldefense.com/v3/__https:/github.com/NetLogo/NetLogo/pull/2023*discussion_r844165495__;Iw!!Dq0X2DkFhyF93HkjWTBQKhk!H4l53tRmfr360_NNQvLgYmMXqrcj8jb_DFRL1grNOtJTypFr5z_EB_CbHz026lXgq513PyHUpg$>:

> @@ -104,7 +104,12 @@ class Tabs(workspace:           GUIWorkspace,

       if (tabManager.getMainCodeTab.dirty) {

         // The SwitchedTabsEvent can lead to compilation. AAB 10/2020

          new AppEvents.SwitchedTabsEvent(tabManager.getMainCodeTab, currentTab).raise(getTabs)

-      }

+       } else {

+         // If the user has switched to the Interface Tab, we must compile any dirty TemporaryCodeTab AAB 3/2022

+         if (interfaceTab.equals(currentTab)) {

+           (externalFileTabs.asInstanceOf[mutable.Set[TemporaryCodeTab]]).foreach(_.compileIfDirty())

Why is this cast necessary? Should the type already be mutable.Set[TemporaryCodeTab]?

________________________________

In netlogo-gui/src/main/app/codetab/TemporaryCodeTab.scala<https://urldefense.com/v3/__https:/github.com/NetLogo/NetLogo/pull/2023*discussion_r844169693__;Iw!!Dq0X2DkFhyF93HkjWTBQKhk!H4l53tRmfr360_NNQvLgYmMXqrcj8jb_DFRL1grNOtJTypFr5z_EB_CbHz026lXgq53qZcw9YQ$>:

>      ignoring(classOf[UserCancelException]) {

-      if(dirty && Dialogs.userWantsToSaveFirst(filenameForDisplay, this))

-        save(false)

+      if(saveNeeded) {

Prefer space after keyword and before opening paren.

**Comment by brandesNW** [comment]
The changes in the draft PR are only intended to address saving of the included files and making sure that the current code for the nls files is executed.

The main changes are intended to ensure that if a included file is open its code should be executed, whether or not the buffer has been saved. When the buffer is closed, the code in the nls file should be executed.

Additionally when an include file buffer is closed a Save/Discard/Cancel dialog should appear if and only if the buffer has changed.

In my opinion if the behavior you refer to is a novel issue. Does it occur only when nls files are involved? It’s probably worth testing the case with no included file, but with a separated code tab.


--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Jeremy B ***@***.***>
Reply-To: NetLogo/NetLogo ***@***.***>
Date: Thursday, April 7, 2022 at 9:50 AM
To: NetLogo/NetLogo ***@***.***>
Cc: Aaron Andre Brandes ***@***.***>, Author ***@***.***>
Subject: Re: [NetLogo/NetLogo] Included file content loses synch with compiled state (PR #2023)


R.e. Issue 1832 there must be some confusion (perhaps I put in the wrong link). I don’t see anything about widgets

Yeah, I did mis-read the issue a little bit, sorry about that. It does have to do with widgets, though, as the original post references changing "a variable on the Interface tab" which would mean a chooser, slider, switch, or input widget. I re-tested this with these changes and it does not seem fixed, though. Here were my steps:

  *   Open your test model
  *   Add a slider, give it some global name, save it
  *   Open the nls file in the code tab
  *   Make a change to it, see the file is dirty (do not save)
  *   Go back to the interface tab, change the value on the slider
  *   Go back to the nls file code tab, hit the save hotkey (Cmd/Ctrl-S). The nls code tab is saved.
  *   Close the model - open a new one, something else, whatever
  *   Load the test model again. Observe the slider is not updated.

Did you expect that issue to be remediated by the changes? Writing that out I'm not sure I would expect the save action to save interface tab changes, but that relates to issues recently discussed about a widget change marking the interface tab "dirty" or not for save prompts.

**Comment by brandesNW** [comment]
With the addition of the "watcher" code to update buffers if the files are changed externally this PR is very out of date, and a new PR is appropriate.

**Pull request closed without merging**
