### PR TITLE
Fix Link breed changes to compare to the old breed instead of the new breed. 

### PR DESCRIPTION
**Pull request by Wolgo**
Change link `setbreed` and `realloc` function to use and pass along the old breed into OldBreed correctly instead of getting the new breed by using getBreed();

### CODE REVIEW

**Comment by Wolgo** [comment]
Should fix issue: #1899

**Review by Wolgo — COMMENTED** [review]
I realize now that this line is problematic as it will throw an error when used. Unlike breedsOwnIndexOf used in turtle, linkBreedsOwnIndexOf throws an error on a null input. 

I don't think anything actually uses the realloc function now which makes it not fail any tests.
(The function is needed because of the interface requiring a realloc with 2 parameters.)

**Comment by SethTisue** [comment]
> I don't think anything actually uses the realloc function now 

hmm, just checking: are you sure? historically, `realloc` was used so that you didn't lose all your turtles (and in general, all your world state) if you e.g. added or removed a `turtles-own` variable in the Code tab.

**Comment by brandesNW** [comment]
Hi Seth and others,
That comment by person making the PR is incorrect, but the code seems to be correct.
It is true that compilation makes use of realloc, as does set breed.

There was a difference between how Turtle realloc  and Link realloc worked which resulted in a bug because the Link version determined the oldBreed incorrectly. To make them consistent he created a three argument version of Link realloc that took oldBreed as an argument. The original realloc nows calls the three arg version with oldBreed = null.


The PR maker was afraid this would fail in the following code in Link.java

      int oldpos = compiling ? oldBreedsOwnIndexOf(oldProgram, getBreed(), name)
          : _world.linkBreedsOwnIndexOf(oldBreed, name);

Because linkBreedsOwnIndexOf explicitly throws an exception if the breed is null.

It took some investigation for me to determine that there is not be a problem because that code is always run in a compiling context.
If you (Seth) know why there is a check for compiling and how that variable could be false, please let me know.


He may also have been concerned because linkBreedsOwnIndexOf explicitly throws an exception if the breed is null

  def linkBreedsOwnIndexOf(breed: AgentSet, name: String): Int = {
    if (breed == null) throw new IllegalArgumentException("invalid breed")
    breedsOwnCache.getOrDefault(breed.printName + "~" + name, NegativeOneInt).intValue
  }

while the Turtle version would also fail, but doesn’t throw an explicit exception:

  def breedsOwnIndexOf(breed: AgentSet, name: String): Int =
    breedsOwnCache.getOrDefault(breed.printName + "~" + name, NegativeOneInt).intValue

Please add any insight you can recall from days past.

Best,
Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling

**Comment by SethTisue** [comment]
> If you (Seth) know why there is a check for compiling and how that variable could be false, please let me know.

ohhhhhh..... boy. I'm afraid I don't remember anything about that :-/

**Comment by SethTisue** [comment]
> If you (Seth) know why there is a check for compiling and how that variable could be false, please let me know.

ohhhhhh..... boy. I'm afraid I don't remember anything about that :-/

(maybe it's just that it will be false when the Code tab is compiled for the first time? but then why wouldn't it be called `recompiling`? 🤷 )

**Pull request merged**
