### PR TITLE
Ignore comments when parsing metrics (#1122)

### PR DESCRIPTION
**Pull request by H-Theking**

### CODE REVIEW

**Comment by mrerrormessage** [comment]
Thanks for spending some time working on this. Unfortunately, this fix doesn't address the issue in the way we need. It *does* fix the error, but it also deletes all whole-line-comment reporters from the behaviorspace experiment. If I edit a BehaviorSpace experiment to add in a whole-line-comment as a reporter, then click OK, then click edit on the same experiment, the comment disappears. Instead of removing the comment when we save, we should be filtering out lines that are comments and excluding them from compilation. This should be done by applying a `.filter` to the `metrics` before they're compiled to reporters in `lab/Worker.scala`.

While we're at it, we can also `.trim` lines in `ProtocolEditable`, which will remove whitespace lines and make it easier to detect whole-line-comments in `lab/Worker.scala`.

**Comment by H-Theking** [comment]
>If I edit a BehaviorSpace experiment to add in a whole-line-comment as a reporter, then click OK, then click edit on the same experiment, the comment disappears.

I happens too with comments in vary variables section.
I've tried this
```val metricProcedures = protocol.metrics.filter(!_startsWith(";")).map(workspace.compileReporter(_))```
and it gives me an exception, I tried to trace it back but I still can't understand the flow
```
java.lang.reflect.InvocationTargetException
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
 at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
 at org.nlogo.awt.EventQueue$.invokeAndWait(EventQueue.scala:19)
 at org.nlogo.awt.EventQueue.invokeAndWait(EventQueue.scala)
 at org.nlogo.window.GUIWorkspace.setDimensions(GUIWorkspace.java:345)
 at org.nlogo.lab.Worker$Runner.setVariables$1(Worker.scala:121)
 at org.nlogo.lab.Worker$Runner.callHelper(Worker.scala:167)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:91)
 at org.nlogo.lab.Worker$Runner.call(Worker.scala:74)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NegativeArraySizeException
 at org.nlogo.agent.World.createPatches(World.java:781)
 at org.nlogo.window.WorldViewSettings.setDimensions(WorldViewSettings.scala:389)
 at org.nlogo.window.WorldViewSettings.setDimensions(WorldViewSettings.scala:374)
 at org.nlogo.window.GUIWorkspace$2.run(GUIWorkspace.java:336)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
 at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
 at java.awt.Dialog.show(Dialog.java:1084)
 at java.awt.Component.show(Component.java:1673)
 at java.awt.Component.setVisible(Component.java:1625)
 at java.awt.Window.setVisible(Window.java:1014)
 at java.awt.Dialog.setVisible(Dialog.java:1005)
 at org.nlogo.lab.gui.Supervisor$$anon$5.run(Supervisor.scala:113)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

>While we're at it, we can also .trim lines in ProtocolEditable, which will remove whitespace lines and make it easier to detect whole-line-comments in lab/Worker.scala.

I think that is already done

**Comment by mrerrormessage** [comment]
@nicolaspayette , you originally opened #1122, how important is it that commented-out reporters not get removed from the list of reporters? Leaving in comments does seems strange when we delete whole-line comments in other fields, but on the other hand it does seem useful to leave in commented lines for debugging and informational purposes. Perhaps we need to consider commented lines in general and not just in this one section of behaviorspace?

**Comment by nicolaspayette** [comment]
> how important is it that commented-out reporters not get removed from the list of reporters?

Very important. The whole point of commenting them out is to be able to quickly re-enable them. It could also be frustrating for a user to unexpectedly lose a complex reporter expression.

> Perhaps we need to consider the behavior for wholly-commented-lines in all cases and not just in this one section of behaviorspace?

Yeah, I think so.

**Comment by H-Theking** [comment]
> Perhaps we need to consider the behavior for wholly-commented-lines in all cases and not just in this one section of behaviorspace?

The comments are removed during the parsing of behaviourspace. Unless the structure of ValueSet is changed to include Strings as values, I don't know how we could keep the comments of the valuesets section.

**Comment by mrerrormessage** [comment]
@nicolaspayette , do you think comments need to be saved as part of the ".nlogo" file, or merely between behaviorspace runs within a single NetLogo "session." It seems there are several ways to solve this problem, but the approach chosen depends on whether we want to save them to a ".nlogo" file or not.

**Comment by nicolaspayette** [comment]
> whether we want to save them to a ".nlogo" file or not.

We want to save them, no doubt. I think it would be surprising (and frustrating) for a user to comment out something and have it disappear when saving/reloading the model!

**Comment by mrerrormessage** [comment]
OK @H-Theking , finishing this will require some substantial work as it will involve changing the structure of `LabProtocol` to have both `metrics` and `valueSets` be lists with optional comments. At the moment `LabProtocol` looks like:

```scala
case class LabProtocol(... metrics: List[String], valueSets: List[ValueSet])
```

After the change it will need to look something like:

```scala
case class LabProtocol(... metricStrings: List[Either[String, String]], valueStrings: List[Either[String, ValueSet]]) {
  //  need to have auxiliary constructor for backwards compatibility
  def this(... metrics: List[String], valueSets: List[ValueSet]) = /*... */ 
  def metrics: List[String] = metricStrings.collect {
    case Right(metric) => metric
  }
  def valueSets: List[ValueSet] = valueStrings.collect {
    case Right(valueSet) => valueSet
  }
}
```

Obviously, the final names might be a little different (`metricStrings` and `valueStrings` aren't great names) and a lot of code will need to be changed elsewhere to accomadate this, but in general this would support what @nicolaspayette has requested. I understand this might be more than you want to take on. If so, just let me know.

**Comment by H-Theking** [comment]
Roger

**Comment by H-Theking** [comment]
I'll attempt that when I have time

**Comment by mrerrormessage** [comment]
This hasn't been touched in 6 months. Closing due to inactivity. If you have interest in continuing, we can reopen.

**Pull request closed without merging**
