### PR TITLE
Add a few hotkeys - jump-to declaration, show usage, and save-all

### PR DESCRIPTION
**Pull request by LaCuneta**
New hotkeys:

- Command-Alt-S: Save-all (for multiple open+dirty includes files)
- Command-U: Show usage
- Command-E: Jump to declaration

If those are bad choices for some reason, I'm open to suggestions for easier-to-use keys.

### CODE REVIEW

**Comment by nicolaspayette** [comment]
> I think command-period is kind of a standard for "jump to definition"?

I don't know about command-period in particular, but any shortcut not involving plain old letters has the potential to be problematic on international keyboard layouts. My Italian colleagues can't use <kbd>Ctrl</kbd>+<kbd>+</kbd> to zoom in, for example, and I can't use <kbd>Ctrl</kbd>+<kbd>/</kbd> to hide the command centre on my French-Canadian keyboard (though the latter is not much of a loss...)

**Comment by LaCuneta** [comment]
So <kbd>Ctrl</kbd>+<kbd>J</kbd> in NetLogo does a "remove end-of-line-break" or "combine with next line" operation.  I can't find a definition for this in the code, so I assume it's a default for the text editor control.  <kbd>Ctrl</kbd>+<kbd>.</kbd> looks to be open, though, if that's better than 'E'.

**Comment by nicolaspayette** [comment]
Related: #1606.

> So <kbd>Ctrl</kbd>+<kbd>J</kbd> in NetLogo does a "remove end-of-line-break" or "combine with next line" operation.

Woah. Never knew that. Does anyone actually use that? Still, I wouldn't want to take it away from big <kbd>Ctrl</kbd>+<kbd>J</kbd> fans out there if there are any.

I think <kbd>Ctrl</kbd>+<kbd>.</kbd> *might* be a problem with the French AZERTY keyboard (which weirdly requires pressing <kbd>Shift</kbd>+<kbd>;</kbd> to get a period).

Keeping <kbd>Ctrl</kbd>+<kbd>E</kbd> seems like the safe option...

**Comment by LaCuneta** [comment]
I did a little more research and didn't find any consistent key for "Jump to..." among editors and IDEs, so I think we'll start with <kbd>Ctrl</kbd>+<kbd>E</kbd> and change later if needed (or maybe move specification to a config file?)

**Pull request merged**
