### PR TITLE
Scala Conversion

### PR DESCRIPTION
**Pull request by Idloj**
Finally done!!!
NetLogo code lines are 2,099 less!

Please check this carefully to see if I have made any changes in behavior that I couldn't catch on compile.

### CODE REVIEW

**Comment by frankduncan** [comment]
Uhm, whoa.  This is incredible.

**Comment by frankduncan** [comment]
Outside of how cool this is, it may not get merged for a while.  There's discussion going on within the program about how 5.x and 6.x lines of development are going to continue, and we need to resolve those before we merge this giant of a change.

**Comment by Idloj** [comment]
I haven't made any change just converted to Scala, so what is the problem?

**Comment by frankduncan** [comment]
5.x and 6.x have diverged so much that merging changes up to 6.x that happen in 5.x is becoming increasing time intensive, and we need to have a bit of a project map to make sure that we don't create too much work for ourselves.

**Comment by Idloj** [comment]
didn't got it

**Comment by qiemem** [comment]
Wow, this is amazing. Well done @Idloj!

**Comment by SethTisue** [comment]
@Idloj, thank you, this looks amazing. but I'm getting some compilation errors: https://gist.github.com/SethTisue/d76fa08d957f814c9285. maybe you have some uncommitted local changes that didn't make it into the PR?

**Comment by Idloj** [comment]
Oh, I didn't make tests just `compile`. I'll fix those and make another commit.

**Comment by frankduncan** [comment]
Cool!  It's also a good thing to run "./nightly.sh" before making a pull request.  That will run all the tests and make sure you didn't have any big regressions.

**Comment by SethTisue** [comment]
when I do `sbt run` I get:

```text
[error] java.util.NoSuchElementException: key not found: org.nlogo.app.Tabs[,0,0,0x0,invalid,layout=ch.randelshofer.quaqua.panther.QuaquaPantherScrollTabbedPaneUI$QuaquaTabbedPaneLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=20971872,maximumSize=,minimumSize=,preferredSize=,haveRegistered=false,tabPlacement=TOP]
[error] 	at scala.collection.MapLike$class.default(MapLike.scala:228)
[error] 	at scala.collection.AbstractMap.default(Map.scala:58)
[error] 	at scala.collection.mutable.HashMap.apply(HashMap.scala:64)
[error] 	at org.nlogo.window.Event.org$nlogo$window$Event$$doRaise(Event.scala:161)
[error] 	at org.nlogo.window.Event.raise(Event.scala:128)
[error] 	at org.nlogo.app.Tabs.stateChanged(Tabs.scala:61)
[error] 	at javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:416)
[error] 	at javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:270)
[error] 	at javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:132)
[error] 	at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:67)
[error] 	at javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:616)
[error] 	at javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:591)
[error] 	at javax.swing.JTabbedPane.insertTab(JTabbedPane.java:731)
[error] 	at javax.swing.JTabbedPane.addTab(JTabbedPane.java:798)
[error] 	at org.nlogo.app.Tabs.init(Tabs.scala:36)
[error] 	at org.nlogo.app.App.org$nlogo$app$App$$finishStartup(App.scala:445)
[error] 	at org.nlogo.app.App$$anonfun$main$3.apply$mcV$sp(App.scala:162)
[error] 	at org.nlogo.swing.Implicits$$anon$17.run(Implicits.scala:13)
[error] 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:302)
[error] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
[error] 	at java.awt.EventQueue.access$200(EventQueue.java:103)
[error] 	at java.awt.EventQueue$3.run(EventQueue.java:694)
[error] 	at java.awt.EventQueue$3.run(EventQueue.java:692)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
[error] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
[error] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
[error] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
[error] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
[error] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
[error] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
[error] 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by Idloj** [comment]
Update: NetLogo code lines are 2,100 less

**Comment by Idloj** [comment]
Update: 2,097 :(

**Comment by mrerrormessage** [comment]
This should be retargeted to use hexy as base branch.

**Comment by Idloj** [comment]
It cause problems with zooming, and I can't figure it out.

**Comment by mrerrormessage** [comment]
Well, I'm going to close this PR. If you want, you can leave the zoomer code in java and convert everything else over.

**Comment by SethTisue** [comment]
The most plausible path forward for something like this is broken up into a series of separate PRs. I'd suggest tackling definitely no more than a single package at a time, and it's normally better to go even finer-grained than that and just convert a single class or a handful of closely related classes.

**Comment by Idloj** [comment]
That was my original plan, one package at a time. But as you can see there are very large packages...

Now that I see the result of this plan, My new plan is one file at a time, and the small files may be converted in one commit.

**Pull request closed without merging**
