### PR TITLE
Implement NotAny Optimization

### PR DESCRIPTION
**Pull request by diparthshah**
This PR introduces ` _equal(_count, _constdouble: 0.0) => _not(_any(*))` optimization. This is also part of GSoC 2019 project.

### CODE REVIEW

**Comment by qiemem** [comment]
Cool! Great idea! Could this be generalized further? Make a `_hasexactly(n, agentset)` which will bale early if the number of matches exceeds `n` or if the number of misses exceeds `count - n`? Then `_equal(_count, _constdouble: n)` could be optimized for all `n`. Could do similar optimizations for the other numeric comparison operators as well.

**Comment by diparthshah** [comment]
Hey @qiemem that sounds like a good idea. My other parts of my GSoC project is too implement:
` _equal(_count, _constdouble: 0.0) => _not(_any(*))`
` _greaterthan(_count, _constdouble: 0.0) => _any(*)`
` _notequal(_count, _constdouble: 0.0) => _any(*)`
and also port them to Tortoise project too. I will surely like to implement your idea after that.

**Comment by qiemem** [comment]
That's great! Consider though:

- You can write these in a way that generalizes for all `n` (since counting is monotonic), so you don't actually need to write special cases for `0`. Just trying to save you work here ;)
- I think you can actually write just one optimized primitive that will do everything, or at least, a primitive that you can instantiate with conditions. Haven't quite worked this out, but basically something that takes a predicate that shouldn't be violated during counting. May not be worth it; just a thought.

**Comment by diparthshah** [comment]
Hey @qiemem , i have made small step according to idea you proposed. 
https://github.com/diparthshah/NetLogo/commit/aad1efbe845f231057cc5c39125129f0af372e5a
Can you check if this is something we are aiming at ?

**Comment by qiemem** [comment]
Don't have time to do a super close look right now, but that definitely looks closer to what I had in mind. I'll add other comments on the code itself. Note that I think there is probably a generalization that would let you get `_greaterthan`, `_lessthan`, etc with the same optimized primitive, but maybe it's better to do them separate first, and then combine once the correct abstraction is apparent.

**Comment by diparthshah** [comment]
Hey @qiemem i read your comments on the code and made some changes accordingly here: https://github.com/diparthshah/NetLogo/commit/de02a192ede90cb44aeced3f7588eeb5c8bd2abd
Let me know if i have understood that correctly. Thanks.

**Comment by diparthshah** [comment]
Here's the dump comparison: https://www.diffchecker.com/mXbHjadq

**Comment by qiemem** [comment]
Commented! The dump doesn't tell us much since it's just calling out to that method now. Have you actually benchmarked it yet?

Oh, I realized one way you could generalize. You could add an `inBounds` method or something that takes a lower bound and upper bound, with signature:

```
def inBounds(lower = 0, upper = Int.MaxValue): Boolean
```

For `=`, set them to the same value. For `>` and `>=`, set lower bound to the appropriate value. For `<` and `<=` set the upper bound. The upper bound gives you a clear early exit criterion and you could also exit early on the lower bound based on `ArrayAgentSet.arraySize` (though this is approximate of course). 

Also, it feels a little funny discussing commits that aren't actually in this PR here, so you might consider adding them to this PR or opening a new one. Also, be good to get input from @LaCuneta or someone else more active in NetLogo than me.

**Comment by diparthshah** [comment]
Hey, @qiemem Thanks for your inputs on this idea. I'll definitely look into it.

**Pull request closed without merging**
