### PR TITLE
Add an asterisk to the title to indicate dirtiness. closes #814

### LINKED ISSUE #814: Add an asterisk in front of the title to indicate if the model was modified since last saved

### PR DESCRIPTION
**Pull request by Idloj**

### CODE REVIEW

**Comment by mrerrormessage** [comment]
The tests are failing on Travis due to running out of Java Heap space. If you rebase against hexy, you may be able to get the build more consistent. Alternatively, if you re-run the build enough times it might start to work.

**Comment by mrerrormessage** [comment]
OK, Travis is now passing, I'll try to test this on Mac/Windows by Friday.

**Comment by mrerrormessage** [comment]
OK, I've tested and here are some things that need to be fixed:

* In Mac "windowModified" should now be "Window.documentModified" (according to this apple doc)[https://developer.apple.com/library/mac/documentation/Java/Conceptual/Java14Development/07-NativePlatformIntegration/NativePlatformIntegration.html]. This wasn't something that you changed, of course, but it is needed to make the mac indicator behave correctly.
* In Windows (and in linux as well, I suspect), the first two characters of a model name get dropped when opening a new model with a dirty model currently loaded. To reproduce:
  * Open any existing model (I opened wolf sheep predation)
  * Make a few changes to get the `*` to show up
  * Choose "New..." and discard changes
  * The title of the frame now reads "tLogo" (screenshot attached)

Once these issues have been resolved, I think this can be merged.

**Comment by Idloj** [comment]
I don't know why but the effect of "tLogo" only happens when you open a model from the Models Library. When I opened a "/tmp/Untitled.nlogo" that I saved a few minutes before it behaved correctly.

**Comment by Idloj** [comment]
I also just noticed that if you open a library model, make a change and "save as" - the first 2 chars are dropped.

**Comment by mrerrormessage** [comment]
OK, I've tested this on Mac and it works great. It no longer seems to work at all on Windows though (I'm no longer seeing the asterisk at all. If you would like, I can merge it (as it represents a forward step for Mac and linux). Otherwise, I can wait for you to investigate the problem. Let me know what you would prefer.

**Comment by Idloj** [comment]
Do you have any idea why would Windows be different?

As for the merging question, I don't have a preference to either side, but if it gets merged I would like an "Asterisk doesn't show on Windows" so we don't forget/lose track about it, and so users don't report a bug we already know about.

**Comment by mrerrormessage** [comment]
@Idloj , I have the following changes to build on Windows, these may or may not be helpful for you:
```diff
$ git diff -- project/build.sbt
diff --git a/project/build.sbt b/project/build.sbt
index 3a68373..6bb99ed 100644
--- a/project/build.sbt
+++ b/project/build.sbt
@@ -3,4 +3,10 @@ scalacOptions += "-deprecation"
 // so we can use native2ascii on Linux.  use JAVA_HOME not the java.home
 // system property because the latter may have "/jre" tacked onto it.
 unmanagedJars in Compile <+= (javaHome) map { home =>
-  home.getOrElse(file(System.getenv("JAVA_HOME"))) / "lib" / "tools.jar" }
+  val jhome: File =
+    if (home == null || home.isEmpty)
+      file("""C:\Program Files\Java\jdk1.8.0_60""")
+    else
+      home.get
+  println(jhome)
+  jhome / "lib" / "tools.jar" }
diff --git a/sbt b/sbt
index 6e41d66..651bbc3 100755
--- a/sbt
+++ b/sbt
@@ -6,7 +6,7 @@
 # an intermediary JH variable --JAB (3/22/13)
 if [[ `uname -s` == *CYGWIN* ]] ; then
   CURR_DIR="$( cd "$( dirname "$0" )" && pwd )"
-  JH=`cygpath -up "\Java\jdk1.8.0_31"`
+  export JH=`cygpath -up "\Program Files\Java\jdk1.8.0_60"`
 else
   CURR_DIR=`dirname $0`
   if [ `uname -s` = Linux ] ; then
@@ -28,6 +28,9 @@ fi

 export PATH=$JH/bin:$PATH
 JAVA=$JH/bin/java
+if [[ `uname -s` == *CYGWIN* ]] ; then
+  JAVA=$JH/bin/java.exe
+fi
 JJS=$JH/bin/jjs

 # Most of these settings are fine for everyone
```

**Comment by SethTisue** [comment]
(For Windows testing usually I just build on Mac or Linux and then drop the resulting JAR into a NetLogo directory in my Windows VM.)

**Comment by Idloj** [comment]
But Windows uses JRE 6, and the JAR file is built using Java 8

**Comment by SethTisue** [comment]
ah, well, for hexy, until somebody tackles https://github.com/NetLogo/NetLogo/issues/193, you'd have to use the no-bundled-Java option; see http://ccl.northwestern.edu/netlogo/docs/faq.html#netlogo_java . but actually, whether installer-building even currently works on hexy at all, I have no idea, maybe it doesn't.

you could work around it by just copying over whatever additional files are needed to make `java -jar NetLogo.jar` work, without going through the official installer at all. the official installer doesn't do anything magic; it just unpacks some files and adds file associations for the `.nlogo` and `.nlogo3d` extensions.

**Comment by Idloj** [comment]
I have just tested on Windows and it works fine.

**Comment by mrerrormessage** [comment]
I'll test again today and hopefully we can get this merged in.

Robert

**Comment by mrerrormessage** [comment]
This looks awesome! Thanks for the pull request.

**Pull request merged**
