### PR TITLE
Median not overflowing unnecessarily

### PR DESCRIPTION
**Pull request by Akarshit**
Similar to #972 
But the fix is easy in this case.
Also removed the `validDouble()` check as `Double / 2 + Double / 2` should be(?) a valid Double.

### CODE REVIEW

**Comment by mrerrormessage** [comment]
While it's true that the median should never be invalid when the all input doubles are valid, we still need to keep this check in. The if one of the numbers involved in the median calculation is a `NaN` or `Infinity` the number returned will also be a `NaN` or `Infinity`. There are ways to get doubles into NetLogo which are beyond our control (extensions) and I want to keep this check so that our double primitives verify that the numbers are correct before returning them.

**Comment by Akarshit** [comment]
@mrerrormessage I would add the check again to this PR only if you could open it.

**Comment by mrerrormessage** [comment]
it isn't needed - `newValidDouble` performs the check and is in the existing code.

**Comment by Akarshit** [comment]
But the change from `(middle1.doubleValue() + middle2.doubleValue()) / 2` to `middle1.doubleValue() / 2 + middle2.doubleValue() / 2` is still needed.

**Comment by mrerrormessage** [comment]
Right, sorry I glossed right over that change. Reopening.

**Comment by Akarshit** [comment]
@mrerrormessage Added the `validDouble` check again.
I will have to run the tests on this one and push those dumps too?

**Comment by mrerrormessage** [comment]
Yes, that's correct. The dumps may not change for this one as I'm not sure how commonly `median` is used, but it's still a best practice when changing primitives.

**Pull request merged**
