### PR TITLE
Add Export Code as HTML feature. fixes #645

### LINKED ISSUE #645: Export code as HTML/PDF

### PR DESCRIPTION
**Pull request by Idloj**
[Review on Reviewable](https://reviewable.io/reviews/netlogo/netlogo/669)

### CODE REVIEW

**Comment by SethTisue** [comment]
any news on this?

**Comment by Idloj** [comment]
What do you mean?

**Comment by SethTisue** [comment]
I'm asking @frankduncan if this is going to be merged.

**Comment by frankduncan** [comment]
@Idloj I don't see the new ExportCodeEvent, and it's not compiling for me because of it.

**Comment by SethTisue** [comment]
@Idloj you may not have realized that the source code for the events is auto-generated. you need to add the event to `project/autogen/events.txt`

**Comment by frankduncan** [comment]
Yeah, that's what it is.  I'm taking care of it really quicklike

**Comment by frankduncan** [comment]
This works really well!  It was easiest for me to do the pull from inside our own repo, so I duplicated it.  Am closing this one :)

**Comment by SethTisue** [comment]
hey @Idloj, 1) thanks for this, 2) the development team hangs out at http://gitter.im/NetLogo/NetLogo if you'd ever like to talk to us

**Pull request merged**
