### PR TITLE
sbt 1.4.9 (was 1.3.13)

### LINKED ISSUE #1980: Fix classpath type in Scaladoc.scala for sbt 1.4+
When trying to update [sbt](https://github.com/sbt/sbt) from 1.3 to a newer 1.4+ version (tested multiple ones), the [following error](https://github.com/EwoutH/NetLogo/runs/4070215159?check_suite_focus=true#step:7:276) pops up:
```
[error] /home/runner/work/NetLogo/NetLogo/project/Scaladoc.scala:47:39: type mismatch;
[error]  found   : Array[xsbti.VirtualFile]
[error]  required: Seq[java.io.File]
[error]           (sources in Compile).value, classpath, out, opts,
[error]                                       ^
```
It refers to [this piece of code](https://github.com/NetLogo/NetLogo/blob/6.2.1/project/Scaladoc.scala#L47) in Scaladoc.scala. I couldn't find anything about it in the - suspiciously small - sbt [migration guide](https://www.scala-sbt.org/sbt-site/migration-guide.html).
Apparently, starting from sbt 1.4, it expects `classpath` to be a `Seq[java.io.File]` type instead of an `Array[xsbti.VirtualFile]`.

I asked @mrerrormessage about this issue in #1553 (where sbt was upgraded to 1.x), and he gave the following, very useful, [reply](https://github.com/NetLogo/NetLogo/pull/1553#issuecomment-964155110):
> Looking through this really takes me back. This appears to have been a breaking change SBT made without telling anyone (surprise!).
> 
> If the question is "how does one turn a classpath into a `Seq[java.io.File]`?" I think the answer can be found [here in the sbt source](https://github.com/sbt/sbt/blob/2dad7ea76385261aa542b5e7410d50d19e1a496a/main/src/main/scala/sbt/Defaults.scala#L2133). The `data` method I believe to be [this one](https://github.com/sbt/sbt/blob/fe5497938a8b2898dcbab49b60e0f2ef53b06c29/internal/util-collection/src/main/scala/sbt/internal/util/Attributes.scala#L270) from `sbt.internal.util.Attributed`. 
> 
> Depending on how much time you are willing to spend on this, the question could become "is this still the best way to generate selective documentation?" It may be possible to use [`Default.docTaskSettings`](https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/Defaults.scala#L2100) with scoping of `scalacOptions` to build this task instead. Although I feel certain I would have tried this and if it had worked I would have used it. But maybe something changed in sbt that would make it work now? This is something I (personally) would try but would not spend more than a few hours on.

I tried some things on [this branch](https://github.com/EwoutH/NetLogo/commits/patch-3), but couldn't work it out (not being a Java or Scala developer makes it difficult).

### PR DESCRIPTION
**Pull request by SethTisue**
fixes #1980

### CODE REVIEW

**Comment by SethTisue** [comment]
I've opened this as a draft because I haven't really tested it. I'm hoping others could actually get it across the finish line.

**Comment by SethTisue** [comment]
hmm, I will see if I can figure out the CI failure, though

**Comment by SethTisue** [comment]
this is very frustrating:

```
sbt:root> headless/apiScaladoc
[info] creating /Users/tisue/nl.hexy/netlogo-headless/target/src_managed/main/org/nlogo/agent/ImportLexer.java
[info] Main Scala API documentation to /Users/tisue/nl.hexy/netlogo-headless/target...
[error] IO error while decoding /Users/tisue/nl.hexy/netlogo-headless/target/src_managed/main/org/nlogo/agent/ImportLexer.java with US-ASCII: /Users/tisue/nl.hexy/netlogo-headless/target/src_managed/main/org/nlogo/agent/ImportLexer.java (No such file or directory)
```

it creates `ImportLexer.java`, but then moments later, that file has disappeared. I have no idea why. enabling `debug` level logging  doesn't produce any clues that I can see

**Comment by SethTisue** [comment]
I’m contemplating trying a different approach here: maybe instead of having a custom `doc`-like task, we should define a subproject that has only the right sources, and then run the standard task within that subproject

**Comment by SethTisue** [comment]
I tried removing the use of `FileFunction.cached`; I tried ripping out JFlex and replacing it with code that just prints some junk to the file directly; I tried sbt 1.4.0 and sbt 1.6.1; none of this helped.

One thing I noticed is that isn't just `ImportLexer.java` that disappears; the entire `netlogo-headless/target/src_managed` directory vanishes.

**Comment by SethTisue** [comment]
Aha, I think I know what's doing the deleting. In sbt, in `Doc.generate`, we see:

```
      log.info(
        "Generating " + logSnip + " for " + label + " sources to " + outputDirectory.absolutePath + "...")
      IO.delete(outputDirectory)
```

but in our log we see:

```
[info] Main Scala API documentation to /Users/tisue/nl.hexy/netlogo-gui/target...
```

this is wrong. the path should end with `target/api`, not just `target`.

**Comment by SethTisue** [comment]
okay fix pushed, but now there are some extension build problems to sort out.

**Comment by SethTisue** [comment]
It isn't that simple; aligning the sbt versions of the extension with the sbt version here doesn't fix it.

The problem is 43ffbbb5520a9c120fc696a4e75a9b0a92cd9d9f, where @mrerrormessage changed the extension building to happen in-process rather than in a separate process. It looks like this depends on sbt internals which have now changed.

I'm not sure whether that approach can be made to work, or whether we should go back to forking separate processes for the extension builds. Either way, this isn't something I can afford to pour more time into personally..

**Comment by LaCuneta** [comment]
That code has caused a separate issue that we've been living with for a while.  Essentially if you use sbt to compile a bundled extension from the NetLogo project, you can no longer run NetLogo via `netlogo/run`.  I opened [an issue about it in the sbt repo](https://github.com/sbt/sbt/issues/4312).  There were a couple suggestions there from eed3si9n on alternatives to try, but the workarounds were easy enough (just run a separate sbt session to package the extension you're testing) that I never made time to see if they would help.  I thought there was an issue in this repo about it, but I haven't been able to locate it.  I'll open one if I can't find it.

Thanks for giving the updates a try; it's good to know that changing that code will alleviate a couple of problems for us.

**Comment by EwoutH** [comment]
> That code has caused a separate issue that we've been living with for a while

What’s the current status of this issue?

**Comment by brandesNW** [comment]
The issue https://github.com/sbt/sbt/issues/4312 has not been resolved

Is https://github.com/NetLogo/NetLogo/issues/1980 the only issue blocking an upgrade to sbt 1.4.9?
Seth noted there that “I did get the main build working, but the extension builds are broken (see my comment on the PR for details) and fixing requires more work than I can afford to provide.”
--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Ewout ter Hoeven ***@***.***>
Date: Sunday, October 30, 2022 at 11:21 AM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [NetLogo/NetLogo] sbt 1.4.9 (was 1.3.13) (PR #1982)

That code has caused a separate issue that we've been living with for a while

What’s the current status of this issue?

**Comment by brandesNW** [comment]
Hi Ewout,
Are you now working with NetLogo 6.3.0 which uses the Java 17 LTS? We also updated the versions of a number of libraries.
Thanks for all the work you have done.
Did you have any PRs you were working on that depended on it?
- Aaron
--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Ewout ter Hoeven ***@***.***>
Date: Sunday, October 30, 2022 at 11:21 AM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [NetLogo/NetLogo] sbt 1.4.9 (was 1.3.13) (PR #1982)

That code has caused a separate issue that we've been living with for a while

What’s the current status of this issue?

**Comment by SethTisue** [comment]
> Is [#1980](https://github.com/NetLogo/NetLogo/issues/1980) the only issue blocking an upgrade to sbt 1.4.9?

I don't think we know that for sure, but it's very plausible there aren't more dragons lurking. I think it's worth gambling on.

Besides, the project probably can't stay on an antique sbt version forever. And newer sbt versions have nice performance improvements, features, compatibility with other updated tooling, and general quality of life improvements that will benefit the entire development effort.

**Comment by EwoutH** [comment]
> Are you now working with NetLogo 6.3.0 which uses the Java 17 LTS?

Yes! I having is run on Java 17 is really great, it's noticeable faster and there are also rendering improvements, especially for high DPI.

> Besides, the project probably can't stay on an antique sbt version forever. 

What would we need to drop (extensions e.d.) to upgrade to sbt 1.4.9?

And should we reconsider out sbt-in-sbt approach (https://github.com/sbt/sbt/issues/4312#issuecomment-412209982)?

**Comment by brandesNW** [comment]
Hi Ewout,
This is not at the top of the stack right now, but is something we would love to do.
What would we need to drop (extensions e.d.) to upgrade to sbt 1.4.9?
And should we reconsider out sbt-in-sbt approach (sbt/sbt#4312 (comment)<https://urldefense.com/v3/__https:/github.com/sbt/sbt/issues/4312*issuecomment-412209982__;Iw!!Dq0X2DkFhyF93HkjWTBQKhk!QKVQ57BgImYwN697BKX4PEE2g_bK5qtzAzoAlq4lX8LUPCuRR6xQUno48zq3xv_vAHdZ8x6RuvCQFJcWP_rkmlR5bCEubFZ9Gg$>)?

  *   Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Ewout ter Hoeven ***@***.***>
Date: Wednesday, November 16, 2022 at 8:12 AM
To: NetLogo/NetLogo ***@***.***>
Cc: Aaron Andre Brandes ***@***.***>, Comment ***@***.***>
Subject: Re: [NetLogo/NetLogo] sbt 1.4.9 (was 1.3.13) (PR #1982)

Are you now working with NetLogo 6.3.0 which uses the Java 17 LTS?

Yes! I having is run on Java 17 is really great, it's noticeable faster and there are also rendering improvements, especially for high DPI.

Besides, the project probably can't stay on an antique sbt version forever.

What would we need to drop (extensions e.d.) to upgrade to sbt 1.4.9?

And should we reconsider out sbt-in-sbt approach (sbt/sbt#4312 (comment)<https://urldefense.com/v3/__https:/github.com/sbt/sbt/issues/4312*issuecomment-412209982__;Iw!!Dq0X2DkFhyF93HkjWTBQKhk!QKVQ57BgImYwN697BKX4PEE2g_bK5qtzAzoAlq4lX8LUPCuRR6xQUno48zq3xv_vAHdZ8x6RuvCQFJcWP_rkmlR5bCEubFZ9Gg$>)?

**Pull request closed without merging**
