### PR TITLE
Upgrade to sbt 1.x

### PR DESCRIPTION
**Pull request by mrerrormessage**
@TheBizzle , I believe this is something that may be of interest to you. I'm planning to merge this as soon as the tests pass, but feel free to leave comments, questions, etc.

### CODE REVIEW

**Comment by SethTisue** [comment]
is there a reason to stop at 1.0.4 and not go all the way to 1.1.0?

**Comment by mrerrormessage** [comment]
I didn't realize 1.1.0 was out. We can go all the way up to 1.1.0 as long as there are no binary compatibility problems.

**Comment by SethTisue** [comment]
> as long as there are no binary compatibility problems

the sbt 1.x series is binary compatible.

**Comment by EwoutH** [comment]
Hi @mrerrormessage! It has been very long ago, but I got stuck on a piece of code that you wrote in this PR. I'm trying to update sbt from 1.3 to a newer version (tested multiple ones), but I'm encountering the [following error](https://github.com/EwoutH/NetLogo/runs/4070215159?check_suite_focus=true#step:7:276):
```
[error] /home/runner/work/NetLogo/NetLogo/project/Scaladoc.scala:47:39: type mismatch;
[error]  found   : Array[xsbti.VirtualFile]
[error]  required: Seq[java.io.File]
[error]           (sources in Compile).value, classpath, out, opts,
[error]                                       ^
```
It refers to [this piece of code](https://github.com/NetLogo/NetLogo/blob/6.2.1/project/Scaladoc.scala#L47) in de Scaladoc.scala, changed in this PR [here](https://github.com/NetLogo/NetLogo/commit/023206f386d09477f1d7a2913f33983c400182f9#diff-747433efaa22d330a58af1b77d2a95155e7699e231474d786901a08bf136f7e3L43-R47). I couldn't find anything about it in the - suspiciously small - sbt [migration guide](https://www.scala-sbt.org/sbt-site/migration-guide.html).

Apparently, starting from sbt 1.4, it expects `classpath` to be a `Seq[java.io.File]` type instead of an `Array[xsbti.VirtualFile]`.

@SethTisue Loved encountering this comment, by the way, must take you way back! And if you know how to fix this issue that's also more than welcome of course.

>    // The regular doc task includes doc for the entire main source tree.  But for the NetLogo
>    // web site we want to document only select classes.  So I copy and pasted
>    // the code for the main doc task and tweaked it. - ST 6/29/12, 7/18/12
>    // sureiscute.com/images/cutepictures/I_Have_No_Idea_What_I_m_Doing.jpg

**Comment by EwoutH** [comment]
Thanks for the extensive reply! I [tried](https://github.com/EwoutH/NetLogo/commits/patch-3) some things, but unfortunately couldn't work it out. So I opened a issue here #1980, and thanks anyway!

**Pull request merged**
