### PR TITLE
Added the format shortcut to Edit menu

### PR DESCRIPTION
**Pull request by Akarshit**
Fix for #831 
The shortcut is still kept to be `Tab` as `Ctrl + Tab` switches the tab to Interface Tab (atleast on Linux)
Had to overload functions in `Menu.scala` as the default function was ORing the mask for menu item by default.

### CODE REVIEW

**Comment by Idloj** [comment]
I think the appropriate name will be "Format" rather than "Indent" (which is more of what "Shift right" does)

**Comment by Akarshit** [comment]
@Idloj 
Done, thanks.

**Comment by mrerrormessage** [comment]
This looks good, I'll need to test and then I'll merge.

**Comment by mrerrormessage** [comment]
Tested and looks good. This is ready for merge, just need you to sign the CLA above.

**Comment by Akarshit** [comment]
@mrerrormessage Done.

**Pull request merged**
